#!/bin/bash
#PBS -N errest
#PBS -P xl04
#PBS -q normal
#PBS -l walltime=48:00:00
#PBS -l mem=64GB
#PBS -l ncpus=16
#PBS -l storage=gdata/xl04+gdata/if89
#PBS -l wd
#PBS -M kirat.alreja@anu.edu.au

module load jellyfish

# Set input and output filenames
INPUT_FILE=/g/data/xl04/ka6418/assembly/tiliqua_rugosa/rTilRug0.5/rTilRug0.5.asm.hp1.1/rTilRug0.5.asm.hp1.1.fasta
OUTPUT_DIR=/g/data/xl04/ka6418/sequence_alignment/script/ausarg/scripts/error-rate-est

# Set k-mer parameters
KMER_SIZE=21
NUM_THREADS=$PBS_NCPUS

# Generate k-mer frequency distribution using Jellyfish
jellyfish count -m $KMER_SIZE -t $NUM_THREADS -s 10G -C $INPUT_FILE -o $OUTPUT_DIR/jellyfish_out
jellyfish histo $OUTPUT_DIR/jellyfish_out > $OUTPUT_DIR/histo.txt

# Analyze k-mer histogram to estimate error rate
awk '{if ($1!=0) print $1"\t"$2}' $OUTPUT_DIR/histo.txt | sort -n -k 1 > $OUTPUT_DIR/histo_sorted.txt
python3 /g/data/xl04/ka6418/sequence_alignment/script/ausarg/scripts/error-rate-est/kmer_error_rate.py $OUTPUT_DIR/histo_sorted.txt > $OUTPUT_DIR/error_rate.txt