#!/bin/bash
#PBS -N cov_generator
#PBS -P xl04
#PBS -q normal
#PBS -l walltime=0:10:00
#PBS -l mem=32GB
#PBS -l ncpus=16
#PBS -l storage=gdata/xl04+gdata/if89
#PBS -l wd
#PBS -M kirat.alreja@anu.edu.au

module load singularity


singularity exec /g/data/xl04/ka6418/busco_downloads/flagger_latest.sif find_blocks_from_table \
 -c /g/data/xl04/ka6418/ausarg/temp/flagger/rTilRug0.5.asm.cov \
 -t /g/data/xl04/ka6418/ausarg/temp/flagger/rTilRug0.5.asm.table \
 -p /g/data/xl04/ka6418/ausarg/temp/flagger/rTilRug0.5