#!/bin/bash
#PBS -N cov_generator
#PBS -P xl04
#PBS -q normal
#PBS -l walltime=1:00:00
#PBS -l mem=64GB
#PBS -l ncpus=32
#PBS -l storage=gdata/xl04+gdata/if89
#PBS -l wd
#PBS -M kirat.alreja@anu.edu.au

module load singularity

singularity exec /g/data/xl04/ka6418/busco_downloads/flagger_latest.sif python3 /home/programs/src/fit_gmm.py \
 --counts /g/data/xl04/ka6418/ausarg/temp/flagger/rTilRug0.5.asm.counts \
 --cov 15 \
 --output /g/data/xl04/ka6418/ausarg/temp/flagger/rTilRug0.5.asm_15.table