#!/bin/bash
#PBS -N rest_pipeline 
#PBS -P xl04
#PBS -q express
#PBS -l walltime=0:05:00
#PBS -l mem=192GB
#PBS -l ncpus=48
#PBS -l storage=gdata/xl04+gdata/if89
#PBS -l wd
#PBS -l jobfs=400GB
#PBS -M kirat.alreja@anu.edu.au

module load singularity


singularity exec /g/data/xl04/ka6418/docker_images/pepper_deepvariant_r0.8.sif run_pepper_margin_deepvariant call_variant \
  -b "/g/data/xl04/ka6418/ausarg-data/flagger_data/bam_outputs/secphase.corrected_secondrun_sorted.bam" \
  -f "/g/data/xl04/ka6418/species/Tiliqua_Rugosa/rTilRug0.5/assembly/rTilRug0.5.asm.fasta" \
  -o "/g/data/xl04/ka6418/ausarg-data/flagger_data/pepper-pipeline-hap1" \
  -t 48 \
  -r haplotype1-0000019 \
  --ont_r9_guppy5_sup 
