#!/bin/bash
#PBS -N to_index
#PBS -P xl04
#PBS -q normal
#PBS -l walltime=5:00:00
#PBS -l mem=64GB
#PBS -l ncpus=32
#PBS -l storage=gdata/xl04+gdata/if89
#PBS -l wd
#PBS -M kirat.alreja@anu.edu.au

module load samtools 
module load singularity

singularity exec \ 
	/g/data/xl04/ka6418/docker_images/secphase_v0.4.0.sif \
	correct_bam \
	-i /g/data/xl04/ka6418/ausarg-data/flagger_data/bam_outputs/output_rTilRug_new_sorted.bam \
	-P /g/data/xl04/ka6418/ausarg-data/flagger_data/secphase/secphase.out.log \
	-o /g/data/xl04/ka6418/ausarg-data/flagger_data/bam_outputs/secphase.corrected.bam \
	--primaryOnly

samtools index -b /g/data/xl04/ka6418/ausarg-data/flagger_data/bam_outputs/secphase.corrected.bam  /g/data/xl04/ka6418/ausarg-data/flagger_data/bam_outputs/secphase.corrected.bam.bai
