#!/bin/bash
#PBS -N flagger_alignment
#PBS -P xl04
#PBS -q normal
#PBS -l walltime=1:00:00
#PBS -l mem=64GB
#PBS -l ncpus=16
#PBS -l storage=gdata/xl04+gdata/if89
#PBS -l wd
#PBS -M kirat.alreja@anu.edu.au

module load samtools

module load singularity

singularity exec /g/data/xl04/ka6418/docker_images/flagger_v0.3.0.sif \
 depth2cov \
 -d /g/data/xl04/ka6418/ausarg-data/flagger_bed_generation/coverage/cov.depth \
 -f /g/data/xl04/ka6418/species/Tiliqua_Rugosa/rTilRug0.5/assembly/rTilRug0.5.asm.fasta.fai \
 -o /g/data/xl04/ka6418/ausarg-data/flagger_bed_generation/coverage/read_alignment.cov ;

singularity exec /g/data/xl04/ka6418/docker_images/flagger_v0.3.0.sif \
 cov2counts \
 -i /g/data/xl04/ka6418/ausarg-data/flagger_bed_generation/coverage/read_alignment.cov \
 -o /g/data/xl04/ka6418/ausarg-data/flagger_bed_generation/coverage/read_alignment.counts ;

singularity exec /g/data/xl04/ka6418/docker_images/flagger_v0.3.0.sif \
 python3 /home/programs/src/fit_gmm.py \
 --counts /g/data/xl04/ka6418/ausarg-data/flagger_bed_generation/coverage/read_alignment.counts \
 --cov 30 \
 --output /g/data/xl04/ka6418/ausarg-data/flagger_bed_generation/coverage/read_alignment.table ;

singularity exec /g/data/xl04/ka6418/docker_images/flagger_v0.3.0.sif \
 find_blocks_from_table \
 -c /g/data/xl04/ka6418/ausarg-data/flagger_bed_generation/coverage/read_alignment.cov \
 -t /g/data/xl04/ka6418/ausarg-data/flagger_bed_generation/coverage/read_alignment.table  \
 -p /g/data/xl04/ka6418/ausarg-data/flagger_bed_generation/bedfiles/TilRug
