#!/bin/bash
#PBS -N busco_gadi
#PBS -P xl04
#PBS -q normal
#PBS -l walltime=48:00:00
#PBS -l mem=192GB
#PBS -l ncpus=48
#PBS -l storage=gdata/xl04+gdata/if89
#PBS -l wd
#PBS -l jobfs=400GB
#PBS -M kirat.alreja@anu.edu.au



module load singularity

# Adjust these paths to your actual file locations
FASTA_FILE="/g/data/xl04/ka6418/species/Tiliqua_Rugosa/rTilRug0.5/assembly/rTilRug0.5.asm.hp1.fasta"
BUSCO_IMG="/g/data/xl04/ka6418/busco-5.4.7.sif"
LINEAGE_DIR="/g/data/xl04/ka6418/busco_downloads/lineages/vertebrata_odb10"
OUTPUT_DIR="/g/data/xl04/ka6418/species/Tiliqua_Rugosa/rTilRug0.5/assembly/evaluation/buscotwo"

singularity exec $BUSCO_IMG busco \
  -i $FASTA_FILE \
  -o $OUTPUT_DIR \
  -l $LINEAGE_DIR \
  -m genome \
  -c 48 \
  --offline 
