#!/bin/bash
#PBS -N busco_gadi
#PBS -P xl04
#PBS -q normal
#PBS -l walltime=6:00:00
#PBS -l mem=192GB
#PBS -l ncpus=48
#PBS -l storage=gdata/xl04+gdata/if89
#PBS -l wd
#PBS -M kirat.alreja@anu.edu.au


./busco_temp.sh -f /g/data/xl04/ausarg_data/Bassiana_duperreyi/assembly/rBasDup0.5.asm.fa -i /g/data/xl04/ka6418/docker_images/busco-5.4.7.sif -l /g/data/xl04/ka6418/docker_images/lineages/vertebrata_odb10