#!/bin/bash
#PBS -N flagger_alignment
#PBS -P xl04
#PBS -q normal
#PBS -l walltime=3:00:00
#PBS -l mem=192GB
#PBS -l ncpus=48
#PBS -l storage=gdata/xl04+gdata/if89
#PBS -l wd
#PBS -M kirat.alreja@anu.edu.au


module load singularity
module load samtools


singularity exec /g/data/xl04/ka6418/docker_images/meryl_1.3--hdbdd923_2.sif meryl count k=15 output merylDB /g/data/xl04/ka6418/species/Tiliqua_Rugosa/rTilRug0.5/assembly/rTilRug0.5.asm.fasta
singularity exec /g/data/xl04/ka6418/docker_images/meryl_1.3--hdbdd923_2.sif meryl print greater-than distinct=0.9998 merylDB > repetitive_k15.txt

singularity exec /g/data/xl04/ka6418/docker_images/winnowmap_2.03.sif winnowmap -W repetitive_k15.txt -ax map-ont -Y -L --eqx --cs -I8g <(cat /g/data/xl04/ka6418/species/Tiliqua_Rugosa/rTilRug0.5/assembly/rTilRug0.5.asm.hp1.fasta /g/data/xl04/ka6418/species/Tiliqua_Rugosa/rTilRug0.5/assembly/rTilRug0.5.asm.hp2.fasta) /g/data/xl04/bpadata/Tiliqua_rugosa/raw/ONT/tiliqua.ont_merged_runs.pass_fastq.gz | \
            samtools view -hb > read_alignment.bam
