#!/bin/bash
#PBS -N flagger_cleaning
#PBS -P xl04
#PBS -q normal
#PBS -l walltime=2:00:00
#PBS -l mem=64GB
#PBS -l ncpus=16
#PBS -l storage=gdata/xl04+gdata/if89
#PBS -l wd
#PBS -M kirat.alreja@anu.edu.au

module load singularity
module load samtools

samtools sort -n -@16 /g/data/xl04/ka6418/ausarg-data/flagger_data/primary_pipeline/read_alignment.bam > /g/data/xl04/ka6418/ausarg-data/flagger_data/primary_pipeline/read_alignment.sorted_qname.bam

singularity exec /g/data/xl04/ka6418/docker_images/secphase_v0.4.0.sif secphase_index -i /g/data/xl04/ka6418/ausarg-data/flagger_data/primary_pipeline/read_alignment.sorted_qname.bam

singularity exec /g/data/xl04/ka6418/docker_images/secphase_v0.4.0.sif secphase --ont -i /g/data/xl04/ka6418/ausarg-data/flagger_data/primary_pipeline/read_alignment.sorted_qname.bam -f /g/data/xl04/ka6418/species/Tiliqua_Rugosa/rTilRug0.5/assembly/rTilRug0.5.asm.fasta --outDir /g/data/xl04/ka6418/ausarg-data/flagger_data/primary_pipeline --threads 16