#!/bin/bash
#PBS -N quality_value
#PBS -P xl04
#PBS -q normal
#PBS -l walltime=5:00:00
#PBS -l mem=192GB
#PBS -l ncpus=48
#PBS -l storage=gdata/xl04+gdata/if89
#PBS -l wd
#PBS -M kirat.alreja@anu.edu.au

module load biopython 

python3 /g/data/xl04/ka6418/ausarg/temp/qv_frequency/qv_frequency_slave.py /g/data/xl04/ausarg_data/Bassiana_duperreyi/raw/ont/350765_AusARG_RamaciottiGarvan_ONTPromethION_PAF30832.fq.gz /g/data/xl04/ka6418/ausarg/temp/qv_frequency/bass_ont_test